# Generated by Django 5.0.4 on 2024-05-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_newsletter_alter_client_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=1500)),
            ],
        ),
        migrations.RenameModel(
            old_name='NewsLetter',
            new_name='NewsLetterEmail',
        ),
    ]
