# Generated by Django 5.0.4 on 2024-05-09 19:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_newslettercontent_rename_newsletter_newsletteremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettercontent',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
