# Generated by Django 5.0.4 on 2024-05-13 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwereMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project_description', models.TextField(max_length=1200)),
                ('project_requirements', models.TextField(max_length=1200)),
                ('project_duration', models.DecimalField(decimal_places=2, max_digits=3)),
                ('project_complexity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.category')),
            ],
        ),
    ]
