# Generated by Django 5.0.4 on 2024-05-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategorySoftwereMaker',
        ),
    ]
