# Generated by Django 5.0.4 on 2024-05-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_rename_category_categorysoftweremaker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategorySoftwereMaker',
            new_name='Category',
        ),
    ]
