# Generated by Django 5.0.4 on 2024-05-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_rename_categorysoftweremaker_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseManagementMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=70)),
                ('contact_email', models.EmailField(max_length=70)),
                ('contact_phone', models.CharField(max_length=20)),
                ('number_of_employees', models.DecimalField(decimal_places=2, max_digits=6)),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_notes', models.TextField(max_length=1200)),
            ],
        ),
    ]
