# Generated by Django 5.0.4 on 2024-05-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_grouprevenuemaker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='softweremaker',
            name='email_client',
            field=models.EmailField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='softweremaker',
            name='name_surname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='softweremaker',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
